### ISSUE TITLE
Display Server #412

### ISSUE THREAD

**Issue by Ofili-Louis** [egojoseph/Redtech-Payment-Request-Service#7]
We want to support multiple windows. We want to support persist alerts after the app code finishes. We want [a bunch of stuff] that strongly suggests a display server.

So: time to extract the old disused WV-relay display service and turn it into a more serious display server capable of fixing some of these problems.

This obsoletes issue

**Comment by egojoseph** [comment]
WV:: Relay not being tested yet.
